--- #YAML:1.0
name:               MojoX-Renderer-CTPP2
version:            0.01
abstract:           CTPP2 renderer for Mojo
author:
    - Victor M Elfimov <victor@sols.ru>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Mojo:        0.9
    HTML::CTPP2  2.5.3
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
